// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRuG0oQSIpziO0buD62yYcvzoto8AmnKE',
    appId: '1:791686976623:web:1ad5969fbac96ede53699a',
    messagingSenderId: '791686976623',
    projectId: 'cooksy-24914',
    authDomain: 'cooksy-24914.firebaseapp.com',
    storageBucket: 'cooksy-24914.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgVp4SYKnFpvr0Vi6cTL1ZdGkTp95a7B4',
    appId: '1:791686976623:android:814de0cbd6c54cad53699a',
    messagingSenderId: '791686976623',
    projectId: 'cooksy-24914',
    storageBucket: 'cooksy-24914.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBVkBhEym1zdFSr5XB9R3OuY-eX6cez7c',
    appId: '1:791686976623:ios:a5af8f522e95ce5953699a',
    messagingSenderId: '791686976623',
    projectId: 'cooksy-24914',
    storageBucket: 'cooksy-24914.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBVkBhEym1zdFSr5XB9R3OuY-eX6cez7c',
    appId: '1:791686976623:ios:a5af8f522e95ce5953699a',
    messagingSenderId: '791686976623',
    projectId: 'cooksy-24914',
    storageBucket: 'cooksy-24914.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRuG0oQSIpziO0buD62yYcvzoto8AmnKE',
    appId: '1:791686976623:web:f698cc1b2207c4b053699a',
    messagingSenderId: '791686976623',
    projectId: 'cooksy-24914',
    authDomain: 'cooksy-24914.firebaseapp.com',
    storageBucket: 'cooksy-24914.firebasestorage.app',
  );
}
